language: ruby
rvm:
  - 2.4.1
  - jruby
before_script:
  - psql -c 'create database bon_voyage_api_test;' -U postgres
script:
  - rake db:migrate
  - rake db:seed
  - bundle exec rspec
services:
  - postgresql
env:
  - NODE_ENV="test"
