language: ruby
rvm:
  - 2.4.1
gemfile:
  - Gemfile
before_script:
  - psql -c 'create database bon_voyage_api_test;' -U postgres
script:
  - bundle exec rake db:rollback
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec
services:
  - postgresql
env:
  - NODE_ENV="test"
